### ISSUE TITLE
Need a tgz archive to install

### ISSUE THREAD

**Issue by DoubleDrachoon** [php/pecl-networking-xmlrpc#5]
How is this module assembled?
I can only download a zip archive from the repository.
To install using the pear install command, I need a tgz archive.

**Comment by cmb69** [comment]
The PECL archive has gzipped tarballs: https://pecl.php.net/package/xmlrpc; these should be found by `pecl install`. However, since the releases are marked as beta, you might need to change the stability.

And generally, I suggest to switch to something else; consider e.g. https://github.com/gggeek/phpxmlrpc.

**Comment by DoubleDrachoon** [comment]
O thank you very much. You are very kind. This is what is needed.

**Comment by cmb69** [comment]
Okay, then this ticket can be closed. :)
